version: '3.9'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 15

  bot:
    build: .
    environment:
      POSTGRES_HOST: db
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: